apiVersion: v1
kind: Service
metadata:
  name: apache-client
  labels:
    app: apache-client
spec:
  type: NodePort
  selector:
    app: apache-client
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30100